baseURL = 'https://ayzatyh.github.io/newsDemo.github.io/'
languageCode = 'en-us'
title = '兰州美食'
theme = 'ananke'
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true   
